spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: lb://AUTH-SERVICE
          predicates:
            - Path=/auth/**
        - id: facility-service
          uri: lb://FACILITY-SERVICE
          predicates:
            - Path=/api/facilities/**

jwt:
  public-key-path: classpath:rsa/publicKey.rsa
